### PR TITLE
Fix rules RE to properly parse target and counts if present

### PR DESCRIPTION
**Pull request by dmick**
Suggested-by: Marcel Patzlaff <m.patzlaff@pilz.de>
Reviewed-by: Dan Mick <dan.mick@redhat.com>
Fixes: https://github.com/larsks/dot-iptables/issues/1

### CODE REVIEW

**Comment by dmick** [comment]
I just included @mcpat's patch from issue #1, as it seems to work and be useful

**Comment by dmick** [comment]
anything ever gonna happen with these PRs?

**Comment by larsks** [comment]
Oh hey, look, there're PRs here.

This one looks fine.

**Comment by dmick** [comment]
;)

**Pull request merged**
